---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr
  annotations:
    nfs.io/storage-path: "data01/sonarr"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: animes
  annotations:
    nfs.io/storage-path: "data02/media/animes"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: series
  annotations:
    nfs.io/storage-path: "data02/media/series"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads
  annotations:
    nfs.io/storage-path: "data02/downloads/series"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
